### ISSUE TITLE
Ingest PSScene3Band v1 backlog into Production

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#29]
After completing https://github.com/NASA-IMPACT/csdap-ingest/issues/88, ingest the corresponding backlog of PSScene3Band v1 granules.

**Comment by chuckwondo** [comment]
In my attempt to slowly ramp up PSScene3Band ingestion, granules for 2015 and 2016 were ingested without a problem, as they had very few granules.

In 2017, the number starts to grow a fair bit. After a bit of Cumulus throttle adjustment, I was able to ingest through the first 6 months of 2017 (a month at a time, using the Cumulus scaling limitation workaround I implemented [see #11]) with relatively few errors (not sure of exact figure yet, but last I checked, under 0.1% due to some lambda function timeouts that I'll have to investigate).

However, when the process hit the month of 2017-07, it managed to discover 76,376 granules, but then crashed due to a memory error, as shown below.

I'm going to post this to the EOSDIS Slack workspace to see if anybody has suggestions. I recall running into the same (or similar) issue in MAAP ages ago, but I'm fairly certain that the fix was to make the DiscoverGranules lambda function and ECS task instead (which sufficed), but I've already done that for CSDA, so I'm a bit puzzled, because I know we successfully discovered roughly 450K granules in one shot for MAAP (GEDI data, IIRC).

However, I believe the issue has to do with the total number of files, not the number of granules. Since MAAP has a 1-to-1 mapping of granules to files, 450K granules equates to 450K files, whereas for CSDA's PSScene3Band granules, the average is about 15 files/granule, so 76376 granules equates to 1,145,640 files (more than twice what we managed on MAAP), and I'm fairly confident that's the problem since the lambda function (naively) attempts to hold that entire list of files in memory at once, which is the whole root of the Cumulus scalability issue I'm trying to work around.

At this point, I'm going to bump the memory size of the machines for the ECS tasks to see if that gets us past this memory issue. Again, I'll also post to the EOSDIS cumulus-internal channel as well to see if anybody has any other ideas.

```plain
...
0170731_215328_0d05","20170731_223344_0c81","20170731_223345_0c81","20170731_223346_0c81","20170731_223346_1_0c81","20170731_230424_0c12","20170731_230426_0c12"],"level":"info","message":"Discovered 76376 granules.","sender":"@cumulus/discover-granules","stackName":"cumulus-prod","timestamp":"2022-02-24T04:02:16.100Z"}
2022-02-24T04:02:17.787000+00:00 Starting task function finished
2022-02-24T04:07:09.956000+00:00 CMA process failed to kill on task failure: {"errno":"EPIPE","code":"EPIPE","syscall":"write"}
2022-02-24T04:07:09.956000+00:00 Waiting up to 2 seconds for CMA child process to exit
2022-02-24T04:07:09.960000+00:00 CMA Exit Code: 1
2022-02-24T04:07:09.960000+00:00 CMA Exit Signal: null
2022-02-24T04:07:09.960000+00:00 CMA Process Kill: false
2022-02-24T04:07:09.960000+00:00 CMA StdErr:
2022-02-24T04:07:09.960000+00:00  warning setting command to loadAndUpdateRemoteEvent
2022-02-24T04:07:09.960000+00:00 warning setting command to loadNestedEvent
2022-02-24T04:07:09.960000+00:00 warning setting command to createNextEvent
2022-02-24T04:07:09.960000+00:00 Unexpected Error <class 'MemoryError'>.
```

**Comment by chuckwondo** [comment]
I bumped the CPU and Memory settings for the ECS tasks, and that allowed the DiscoverGranules step to avoid the memory error, but then the QueueGranules step failed with a memory error.

However, I believe this happened to be okay for this run because I ingested only for 2017-07, not for any subsequent months, so I believe all of the granules for 2017-07 were queued and then ingested, even though the queuing step ran out of memory. I believe the memory issue occurred after the granules were queued, and just before transitioning out of the queuing step in the step function. I was able to see that 75568 out of 76376 were published to the CMR, leaving 808 that failed for one reason or another (to be analyzed), which is ~1% failure rate (higher than I'd like to see, given that 1% of 2.3M is 23K).

The Cumulus folks are going to do some investigation because I also found that the discovery step for those ~76K granules took nearly 2 hours! That seems much longer than necessary, although for this collection, that equates to ~1.1M files. However, since discovery is essentially just listing files, even listing ~1.1M files should only take a few minutes.

Now I'm going to bump the EC2 instance type up from t3.medium to t3.large, and bump the ECS tasks' CPU and Mem even more, and try again, but this time I'm moving on the 2017-08 since 99% of 2017-07 was successfully ingested. We can come back later and rerun the failures.

**Comment by chuckwondo** [comment]
Success!

After bumping the EC2 instance type to t3.large, task CPU to 768, and task mem reservation to 2048, running ingestion for 2017-08 successfully discovered 116423 granules, and successfully ingested/published 116388 of them, leaving only 35 errors (0.03%)!

Further, although the discovery step itself took ~2h 45m (that's horrendous, but it worked), the ingestion took roughly the same amount of time (~2h 53m). That works out to an ingest/publish rate of ~674 granules/min, which is a very nice rate, but is well within the 2000/min max that the CMR team recommended, so we should not be straining the CMR.

Under ideal conditions, such as experienced during this run, that equates to under 2.5 days to ingest the remaining ~2.3M granules.

Given that, I'm going to kick off ingestion of 2017 Q4. If that looks good (perhaps end of day today), I'll kick off all of the remainder (2018-01 through 2021-12).

However, I may hold off on further ingestion until I get some info back from the Cumulus team (expected this morning). I noticed that in the Cumulus DB, successfully ingested granules in the Dynamo DB granules table have their published attribute set to False instead of True, so I'm in conversation to find out why that's the case. If I can fix this easily, then I'll want to do so before running more ingestion jobs.

**Comment by chuckwondo** [comment]
I found out why our published granules are not marked as "published" in the Cumulus DB. The issue is that our cmr.json files contain `GranuleUR` values that are prefixed with the collection name (e.g., `PSScene3Band-20170801_053801_0c65`), but the corresponding file names for the granule do not include the prefix (e.g., `20170801_053801_0c65_cmr.json`).

Since Cumulus derives the granuleId by using a regex to extract it from the file names, the granuleId excludes the prefix (e.g., `20170801_053801_0c65`) since the file names exclude the prefix. During the step that publishes the metadata to CMR, there is a step that ends up trying to match up the `granuleId`s to the `GranuleUR`s, but since they don't match for us (because our IDs are not prefixed and our URs are), the granules are not updated to indicate that they've been published.

There are several ways to address this, but the 2 simplest ones are:

1. Add a custom task into our workflow that will add the prefixes to the granuleIds before the step that attempts to match things up (that way, things will match up)
2. Update our cmr.json files by removing the prefixes from the GranuleURs

With option 1, we have to add to our Cumulus code, but with option 2, we have to update our code in the `csdap-ingest` repo, where the cmr.json files are generated, because that's where the `GranuleUR` is set to the value of the `id` from the corresponding STAC record.

Either way, we have to modify code somewhere. However, with the first option, we _might_ be able to avoid the cost of re-ingestion because we _might_ be able to perform a bulk operation that would simply re-publish to the CMR, which would update the granule records in Cumulus properly.

I'll raise this in our next standup call to see how we want to address this.

**Comment by chuckwondo** [comment]
After further discussion with the Cumulus team, it appears that the cleanest, safest thing to do is take a rather brute-force approach:

1. Bulk delete all granules
2. Add a new task between the discover and queue steps that will add the missing prefix to the granule IDs
3. Reingest everything

Although this is brute-force, it avoids a number of potential problems that we would otherwise need to deal with, which might end up causing other problems.

**Comment by chuckwondo** [comment]
I created #32 to address the granuleId/GranuleUR mismatch issue that prevents successfully ingested/published granules from being marked as "published."

**Comment by chuckwondo** [comment]
This is blocked until we resolve the remaining metrics configuration details (#39). Once metrics configuration is sorted out, I will retry ingestion of this backlog.

**Comment by chuckwondo** [comment]
All metrics integrations in both UAT (#39) and Prod (#44, with the exception of distribution, but this is not a blocker) are completed and tested.

However, while @HicksMatthew and I were pairing on Cumulus today, we discovered (no pun intended) that Cumulus didn't discover 3 files per granule for the Planet backlog ingestion:

1. `<GRANULE_ID>_Visual_metadata.xml`
2. `<GRANULE_ID>_Visual.tif`
3. `thumb`

The first 2 are because the regex that is configured for the collection for Cumulus to extract granule IDs from the file names inadvertently failed to match them. I have adjusted the regex and confirmed that it now matches them (and still matches all of the others as well).

However, for the thumbnails (thumb files), we have 2 problems:

1. All thumbnail files are named thumb, and thus do not include the Granule ID as a prefix, like all other files do. This means that, as named, they will never be ingested by Cumulus, since they will never match the collection's regex.
1. None of the thumbnail files exist in the MCP source bucket `ss-ingest-prod-ingesteddata-uswest2`, so even if they were named appropriately, they aren't in the same bucket as the rest of the files, so they won't be discovered. This is because they were never copied/moved to that bucket like the rest of the files because they exist in the MCP bucket `ss-ingest-dev-thumbnails115905a6-1qhb7abvyj8pc`, and the rest of the files were copied from the MCP bucket `ss-ingest-dev-ingesteddatac45dd6b6-1w456hbx7scex` when we copied from `us-east-1` to `us-west-2`, as we didn't realize the thumbnails were in a different bucket.

So, the first question is, do we need these thumbnails?

Assuming that we do, that means we need to:

1. Copy them to `ss-ingest-prod-ingesteddata-uswest2`
1. While copying, add the Granule IDs as prefixes to the file names (i.e., `<GRANULE_ID>_thumb`) in order for Cumulus to be able to associate them with the rest of the files for a granule.

I can use S3 Batch to handle this, but, the second question is, would there be any problem with adding the prefixes to the file names? That is, would there be anything that would expect or require the files to be named exactly `thumb`, rather than `<GRANULE_ID>_thumb`?

**Comment by chuckwondo** [comment]
I have addressed the thumbnail and "visual" file issues above, so all of the granule files are now in place and discoverable.

However, after an initial smoke test for ingesting PSScene3Band granules from 2015 (368 granules), although all expected files were discovered, the ingest/pub workflow failed 13 out of 74 times [ceiling(368 / 5) = 74, since granules are configured to be queued in groups of 5] due to the following error:

```plain
{
  "error": "CumulusMessageAdapterExecutionError",
  "cause": {
    "errorType": "CumulusMessageAdapterExecutionError",
    "errorMessage": "CMA process failed (undefined)\n\n                 Trace: spawn ENOMEM}\n\n\n\n                 STDERR: ",
    "trace": [
      "CumulusMessageAdapterExecutionError: CMA process failed (undefined)",
      "",
      "                 Trace: spawn ENOMEM}",
      "",
      "",
      "",
      "                 STDERR: ",
      "    at invokeCumulusMessageAdapter (/var/task/webpack:/node_modules/@cumulus/cumulus-message-adapter-js/dist/cma.js:98:1)",
      "    at Object.runCumulusTask (/var/task/webpack:/node_modules/@cumulus/cumulus-message-adapter-js/dist/cma.js:172:47)",
      "    at Runtime.handler (/var/task/webpack:/index.js:159:10)"
    ]
  }
}
```

I ran into this issue earlier, but after applying a suggestion from the Cumulus team, it appeared to be resolved, but that was in the context of discovering/ingesting a smaller number of granules (89).

Unfortunately, Cumulus does not currently support configuring the memory size of lambda functions (the `PostToCmr` lambda function appears to cause this), so it appears that the only current option is to move the offending lambda function to and ECS task.

**Comment by chuckwondo** [comment]
See #55, but I've managed to ingest years 2015 and 2016.

All 368 granules for 2015 were successfully ingested, and for 2016, 9553 of 9562 granules were ingested and published to the CMR. The following granules from 2016 appear to be missing their CMR metadata files:

1. `PSScene3Band-20160831_212703_0c43`
1. `PSScene3Band-20161030_175856_0e3a`
1. `PSScene3Band-20161030_175859_0e3a`
1. `PSScene3Band-20161030_175900_0e3a`
1. `PSScene3Band-20161030_214135_0c12`
1. `PSScene3Band-20161030_214137_0c12`
1. `PSScene3Band-20161030_214140_0c12`
1. `PSScene3Band-20161030_214220_0c56`
1. `PSScene3Band-20161030_214222_0c56`

These were handled by the following failed workflow executions, failing in `PostToCmr`:

1. `arn:aws:states:us-west-2:339197775982:execution:cumulus-prod-IngestAndPublishGranule:a3d8c9e0-6d1d-4416-b978-dd22e31f2ab4`
   1. `PSScene3Band-20160831_212235_0c37` (succeeded)
   1. `PSScene3Band-20160831_212236_0c37` (succeeded)
   1. `PSScene3Band-20160831_212703_0c43`
1. `arn:aws:states:us-west-2:339197775982:execution:cumulus-prod-IngestAndPublishGranule:f3c186e1-6e5f-4180-afe5-32d916aeaf3e`
   1. `PSScene3Band-20161030_214135_0c12`
   3. `PSScene3Band-20161030_214137_0c12`
   4. `PSScene3Band-20161030_214140_0c12`
   5. `PSScene3Band-20161030_214220_0c56`
   6. `PSScene3Band-20161030_214222_0c56`
1. `arn:aws:states:us-west-2:339197775982:execution:cumulus-prod-IngestAndPublishGranule:7863caca-5290-4edc-a063-771cae7c028e`
   1. `PSScene3Band-20161030_154320_0e30` (succeeded)
   1. `PSScene3Band-20161030_154321_0e30` (succeeded)
   1. `PSScene3Band-20161030_175856_0e3a`
   1. `PSScene3Band-20161030_175859_0e3a`
   1. `PSScene3Band-20161030_175900_0e3a`

The ingestion for 2016 took ~45 min, giving an ingestion rate of ~212 granules/min (`execution_limit` of 100), which I'm going to try to dial up to ~265/min (by setting `execution_limit` to 125).

Regarding the errors, I don't know if this matters, but 2 of the 3 errors show a stack trace of this form, where 1 specific granule ID is mentioned:

```json
{
  "errorType": "CMRMetaFileNotFound",
  "errorMessage": "CMR Meta file not found for granule PSScene3Band-20161030_175856_0e3a",
  "trace": [
    "CMRMetaFileNotFound: CMR Meta file not found for granule PSScene3Band-20161030_175856_0e3a",
    "    at forEach (/var/task/webpack:/index.js:83:13)",
    "    at Array.forEach (<anonymous>)",
    "    at checkForMetadata (/var/task/webpack:/index.js:81:12)",
    "    at postToCMR (/var/task/webpack:/index.js:118:36)",
    "    at Object.runCumulusTask (/var/task/webpack:/node_modules/@cumulus/cumulus-message-adapter-js/dist/cma.js:218:1)",
    "    at runMicrotasks (<anonymous>)",
    "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "    at Runtime.handler (/var/task/webpack:/index.js:159:10)"
  ]
}
```

The other (`f3c186e1-6e5f-4180-afe5-32d916aeaf3e`) shows this error, which does not include a granule ID, but the difference is that this failed on the first granule in the list, whereas the other 2 failed _after_ the first granule:

```json
{
  "errorType": "CMRMetaFileNotFound",
  "errorMessage": "No CMR Meta file found.",
  "trace": [
    "CMRMetaFileNotFound: No CMR Meta file found.",
    "    at checkForMetadata (/var/task/webpack:/index.js:78:11)",
    "    at postToCMR (/var/task/webpack:/index.js:118:36)",
    "    at Object.runCumulusTask (/var/task/webpack:/node_modules/@cumulus/cumulus-message-adapter-js/dist/cma.js:218:1)",
    "    at runMicrotasks (<anonymous>)",
    "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "    at Runtime.handler (/var/task/webpack:/index.js:159:10)"
  ]
}
```

**Comment by chuckwondo** [comment]
Updated memory in Prod for ECS tasks (#61) and added a new rule (`PSScene3Band___1_201709_201712`) to ingest granules from 2017-09 through 2017-12.

Kicked off rule on July 1 at 3:45 PM Eastern, and will update stats/errors in previous comment.

**Comment by chuckwondo** [comment]
Discovery of granules in Sep 2017 completed, discovering 135,145 granules, which was likely somewhere around `18 * 135,145 = 2,432,610` files, which was apparently enough to cause the CMA (Cumulus Message Adapter) to run out of memory.

This is the error shown in the failed step of the execution (`arn:aws:states:us-west-2:339197775982:execution:cumulus-prod-DiscoverAndQueueGranules:fe8bc0a4-6366-42d6-9460-6a2b531d13b7`):

```
warning setting command to loadAndUpdateRemoteEvent
Starting load_remote_event
Ending load_remote_event
warning setting command to loadNestedEvent
Unexpected Error <class 'MemoryError'>. 
```

The details from the CloudWatch log for QueueGranules shows this:

```
Info: No CMA timeout buffer dump set, as lambda is not running as a lambda
CMA process failed to kill on task failure: 
{
    "errno": "EPIPE",
    "code": "EPIPE",
    "syscall": "write"
}
Waiting up to 2 seconds for CMA child process to exit
CMA Exit Code: 1
CMA Exit Signal: null
CMA Process Kill: false
CMA StdErr: 
 warning setting command to loadAndUpdateRemoteEvent
Starting load_remote_event
Ending load_remote_event
warning setting command to loadNestedEvent
Unexpected Error <class 'MemoryError'>. 
```

I'll report this to the Cumulus team, but It appears that we're going to have to dial down our "discovery chunk size" from 1 month. Unfortunately, as our "auto-chunking" workaround is currently written, we will have to do some rework to allow a chunk size between 1 day and 1 month in size, since the "days" is the next smaller date unit than "months", but a 1-day chunk size is far too small, causing far too many events in the workflow (i.e., it will cause the workflow to exceed the [StepFunction event limit](https://docs.aws.amazon.com/step-functions/latest/dg/limits-overview.html) of 25,000 events, if we were to create a rule to discover multiple years of data, and thus cause the workflow to fail).

I believe we might simply have to write a custom DiscoverGranules lambda handler to chunk granules in groups of a configurable size (looks like 5K would be reasonable to keep within 10 min, allowing use of Lambda function, rather than ECS task, or perhaps 10K-25K, if using an ECS task, but note that 50K takes about 90 minutes for discovery [S3]). This would avoid the naming convention we currently require (YYYYMMDD) in the filenames, and would also avoid the size variability that we're running into now.

**Comment by chuckwondo** [comment]
After considering possible redesign effort for DiscoverGranules, while we will certainly need to redesign it to accommodate collections where filenames do not support the naming convention currently required, we can postpone it for now. After also doing some calculations, we can reduce our chunk size from 1 month to 1 day without exceeding the StepFunction event limit (25,000), as there are an average of only 6 events per day in the DiscoverAndQueueGranules workflow, which equates to 6 steps/day * 365 days/year = 2190 steps/year, so we could process 10 years worth of data and still remain within the limit. Since I'm only going to process 4 full years (2018-2021) in one go, after completing the remainder of 2017 successfully, we're well within the limit.

I have adjusted the rule to ingest Sep-Dec 2017 using a 1-day chunk size and kicked things off again. Given that there are ~135K granules in Sep 2017, this should give us ~4500 granules per day, on average, so we should in no way come close to any "out of memory" errors. In fact, this might actually speed things up a bit, given that discovering an entire month's worth of granules can take _hours_, which block the QueueGranules step, which can also take quite some time, thus leaving potential gaps in the ability to parallelize work (i.e., queuing might be sitting idle while discovery is in progress). Given the much smaller chunks, we are likely reducing bottlenecks.

**Comment by chuckwondo** [comment]
After increasing the size of the ES cluster in Prod (see #62), and also updating our Cumulus rule to use an chunk size of 1 day, rather than 1 month (which was still too large in some cases, thus leading to "out of memory" errors), I reran the ingestion for 2017.

To avoid unnecessary (duplicate) egress costs for granules that were already ingested for 2017, I set "duplicateHandling" to "skip". Unfortunately, this failed to work, due to how we form granule IDs (see #32). Therefore, I had to reset "duplicateHandling" to "replace". I have created #65 to address this issue.

Fortunately, after resetting "duplicateHandling" back to "replace," and using a chunk size of 1 day, all of 2017 was ingested without issue (other than a very small percentage of ingest errors, to be expected when ingesting such a large volume of files).

I have also kicked off ingestion of all of 2018, which is currently ingesting July data, and still without any unexpected errors.

At this rate, if all continues without issue, I expect to have 2018 through 2020 fully ingested over the weekend. Regarding 2021, I have to see how much is available for ingestion.

Once 2020 is completed, I will gather stats on granule counts, timings, and failures (with categories), and update this ticket with the stats.

**Comment by chuckwondo** [comment]
Since I've had to reingest 2017 with a smaller chunk size (1 day, not 1 month), I'm starting with new stats:

Workflow: `cumulus-prod-DiscoverAndQueueGranules`

|Year|Execution|Start time|End time|Elapsed (minutes)|Granule count|Rate (granules/min)
|---:|:---|:---|:---|---:|---:|---:
|2017|c17ed3e5-8ee5-4e75-9291-c2881ca1585a|Jul 6, 2022, 13:41:09.948 (EDT)|Jul 7, 2022, 18:43:55.929 (EDT)|1743|618292|355

**Comment by chuckwondo** [comment]
In addition to the 458 IngestAndPublishGranule workflows with a status of `"failed"`, there are 3 with a status of `"running"`, which must be investigated to determine (a) why they're still marked as `"running"` (perhaps a Cumulus bug?), and (b) whether or not the corresponding granules were processed (if not, then the executions must be rerun, just as if the statuses were `"failed"`).

Here are the error types and counts:

```plain
  '503': 1,
  TypeError: 184,
  CMRMetaFileNotFound: 195,
  StreamContentLengthMismatch: 42,
  TimeoutError: 6,
  SlowDown: 3,
  undefined: 4,
  CMRInternalError: 25,
  InternalError: 1
```

The 195 `CMRMetaFileNotFound` errors are due to just what they sound like: missing CMR metadata files. These 195 errors correspond to 195 * 5 = 975 granules, so the granule IDs must be gathered in order to generate the missing CMR files.

The remainder of the errors appear to be transient, so rerunning all of the failed executions (once the missing CMR files are generated) _should_ address all the errors, without need for code or config changes.

**Comment by chuckwondo** [comment]
I am closing this as completed, and have opened the following new issues to address the errors noted in the previous comment: #66, #67
