### ISSUE TITLE
Configure integrations with Cloud Metrics in UAT

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#39]
Work with Metrics team to obtain necessary configuration details to [configure CloudWatch logs delivery](https://nasa.github.io/cumulus/docs/additional-deployment-options/cloudwatch-logs-delivery).

This should be what is necessary to support bulk operations (at least bulk deleting granules).

Acceptance criteria: successful bulk deletion of a small sample of test granules (in UAT) via the Cumulus API using an Elasticsearch query (_not_ a specific list of granule IDs)

Cloud Metrics integrations must be configured:

- [x] Collection creation (SNS topic -> SQS queue subscription)
- [x] Granule ingest (SNS topic -> SQS queue subscription)
- [x] Granule archive (SNS topic -> SQS queue subscription)
- [x] Granule archive delete (SNS topic -> SQS queue subscription)
- [x] Executions (SNS topic -> SQS queue subscription)
- [x] Granule file distribution
  - [x] S3 server access logging
  - [x] S3 bucket replication
  - [x] S3 cross-account permissions
  - [x] Request Cloudfront URL
  - [x] Configure Cloudfront URL
  - [x] Request Cognito account
  - [x] Configure Cognito account

Acceptance criteria:

- [x] Cloud Metrics receives a message when a collection is created
- [x] Cloud Metrics receives a message when a granule is ingested
- [x] Cloud Metrics receives a message when a granule is deleted
- [x] Cloud Metrics receives a message when an execution is started
- [x] Cloud Metrics receives a message when an execution is completed
- [x] Successfully initiate download via the UAT CMR via Cognito authentication
- [x] Cloud Metrics receives a message when a download request is authorized and initiated

**Comment by chuckwondo** [comment]
Added Cumulus configuration for ESDIS Metrics credentials, which now allows performing a `bulk-delete` operation using an Elasticsearch (ES) query via the Cumulus API. Now, rather than immediately producing an error message, an async operation is created and executed. However, there appears to be addition configuration that is missing because the async operation fails:

```plain
  {
    "output": "{\"name\":\"ConnectionError\",\"message\":\"getaddrinfo ENOTFOUND https\",\"stack\":\"ConnectionError: getaddrinfo ENOTFOUND https\\n    at onResponse (/home/task/lambda-function/es-client/node_modules/@elastic/elasticsearch/lib/Transport.js:207:1)\\n    at ClientRequest.<anonymous> (/home/task/lambda-function/es-client/node_modules/@elastic/elasticsearch/lib/Connection.js:99:1)\\n    at ClientRequest.emit (events.js:314:20)\\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\\n    at TLSSocket.socketErrorListener (_http_client.js:427:9)\\n    at TLSSocket.emit (events.js:314:20)\\n    at TLSSocket.EventEmitter.emit (domain.js:483:12)\\n    at emitErrorNT (internal/streams/destroy.js:92:8)\\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\"}",
    "createdAt": 1648160500243,
    "taskArn": "arn:aws:ecs:us-west-2:852078737469:task/cumulus-chuckwondo-CumulusECSCluster/013cdf4dc8ce4957b9438fafebe23215",
    "description": "Bulk granule deletion",
    "operationType": "Bulk Granule Delete",
    "id": "a618142d-211c-468c-9c62-5359fea63798",
    "status": "TASK_FAILED",
    "updatedAt": 1648160540840,
    "timestamp": 1648160541866
  },
```

This part of the error seems to indicate that there is some URL that is missing, as `https` is obviously not a full URL:

```plain
getaddrinfo ENOTFOUND https
```

@HicksMatthew and I are in communication with Amanda on the metrics team to sort this out, along with any other metrics configuration that may be required but missing.

**Comment by chuckwondo** [comment]
Met twice with Amanda Monteavaro and Jonathan Blake from Cloud Metrics team to attempt to recreate required subscriptions in UAT between Cumulus SNS Topics and Metrics SQS Queues to no avail.

I opened a support ticket with AWS for assistance in deleting pending subscriptions requests that we could either not see or not clear on either end (neither on Cumulus end, nor on Metrics end).

AWS responded in under 24 hours and cleared 3 of the pending subscriptions, and requested confirmation on 5 others. I replied to confirm, and am currently waiting for AWS Support to clear the remaining 5. Once they have done so, I will reach out to Amanda again to coordinate an attempt to recreate the necessary subscriptions.

If we are still unable to do so, I will recreate our UAT Cumulus stack, but with a different name prefix, which should then allow us to create the necessary subscriptions. We're rather confident that this final trick, if necessary, should work, as we were earlier able to create a subscription between a Cumulus SNS Topic and a dummy Metrics SQS Queue, so we know it is not an issue related to cross-account subscriptions between our accounts, but rather, it is related to the use of existing names for resources.

cc: @HicksMatthew @jsrikish

**Comment by chuckwondo** [comment]
I received email from AWS support indicating that they have cleared the remainder of the pending subscriptions. I have confirmed via the AWS Console that I no longer see pending subscriptions for the following complete list of SNS topics:

- csdap-uat-report-collections-topic
- csdap-uat-report-executions-topic
- csdap-uat-report-granules-topic
- csdap-uat-report-pdrs-topic

The next step is to meet again with Cloud Metrics to again attempt to create the relevant subscriptions to their SQS queues.

**Comment by chuckwondo** [comment]
I met with Jonathan and Ben from Cloud Metrics to attempt to recreate the SNS->SQS subscriptions, but we were still unable to do so, even after AWS Support cleared the pending subscriptions that we were unable to clear ourselves (and were not automatically expiring after more than 3 days).

The next step is for me to recreate the UAT Cumulus deployment using a different prefix for AWS resources (`cumulus-uat` instead of `csdap-uat` -- on a good note, that will at least be consistent with the convention used for Prod [`cumulus-prod`] and SIT [`cumulus-sit`], as well as for dev stacks [`cumulus-*`])

**Comment by chuckwondo** [comment]
I finally sorted out the SNS -> SQS subscriptions issues with Cloud Metrics. The problem was that they didn't see the subscription requests coming from our end because their system was immediately consuming messages. This was because they had previously configured their Kibana system to consume messages, so things were working as expected.

However, we still needed to confirm the subscriptions somehow, so we ended up adjusting the access policies on the SNS topics so that they could create the subscriptions from their end, rather than requesting them from our end.

Once we made the SNS -> SQS subscriptions, I attempted to ingest some "smoke test" data, but ran into an error in our Cumulus CLI, so we will reschedule our testing session once I resolve the issue.

**Comment by chuckwondo** [comment]
I resolved the error in the Cumulus CLI and was able to add a provider, collection, and rule. Further, metrics received the expected "collection created" message.

However, when I attempted to ingest a few granules, an "access denied" error occurred during the "discovery" step. It turned out that the source bucket in GCC/MCP had its policy changed, which removed permission for our UAT account to read from it. Aaron resubmitted the original NAMS request to restore our permission to read from the bucket.

Once the bucket policy is restored, I will continue with the remainder of the tests.

**Comment by chuckwondo** [comment]
Configuration and testing w/Cloud Metrics is nearly done. We have only distribution to test. At this point, there are 2 semi-blocking issues:

- Attempting to download a published granule file from UAT Earthdata Search should trigger prompt for Cognito creds, but instead produces "internal server error." I've opened a [NASD ticket](https://bugs.earthdata.nasa.gov/browse/NASD-3046) for this.
- During ingest of 9 sample granules, the PostToCmr lambda function ran out of memory. Rerunning the ingest succeeded, but the memory usage is a serious concern for running real ingest jobs, so I've engaged the Cumulus team to investigate (in progress).

**Comment by chuckwondo** [comment]
The snafu with distribution/Cognito was my fault. When I rebuilt UAT, the distribution API Gateway host changed, so I should have submitted a NASD ticket to have the relevant CloudFront URL configuration updated.

NGAP has corrected this, and prompting for Cognito creds works again.

The only thing left is to correct is that the triggered download did not send a message over to Cloud Metrics, but this isn't a blocker.

Regarding the memory issue with PostToCmr, I upgraded CMA to v2.0.2, deployed to UAT, and ingested 89 granules to trigger more (18) back-to-back runs of PostToCmr. They all ran with no more than 221 MB, which is hopefully enough wiggle room within the 256 MB max.

**Comment by chuckwondo** [comment]
I found messages in Kibana showing distribution. For example (sensitive values redacted):

```
csdap-uat-protected [06/May/2022:21:53:01 +0000] 44.203.32.242 arn:aws:sts::852078737469:assumed-role/cumulus-uat-lambda-distribution-api-gateway/cumulus-uat-DistributionApiEndpoints STKPT3VPFP2WJ9X6 REST.GET.OBJECT planet/PSScene3Band/20171201_031959_0f31_3B_Analytic_metadata.xml "GET /planet/PSScene3Band/20171201_031959_0f31_3B_Analytic_metadata.xml
```

It looks like S3 access log delivery can be delayed up to 3 days, so this may be why I didn't not see distribution messages in Kibana soon after I performed downloads.
