### ISSUE TITLE
PostToCmr lambda function frequently fails due to "out of memory" error

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#55]
During execution of the `IngestAndPublishGranule` workflow, the `PostToCmr` lambda function frequently fails with the following error:

```json
{
  "error": "CumulusMessageAdapterExecutionError",
  "cause": {
    "errorType": "CumulusMessageAdapterExecutionError",
    "errorMessage": "CMA process failed (undefined)\n\n                 Trace: spawn ENOMEM}\n\n\n\n                 STDERR: ",
    "trace": [
      "CumulusMessageAdapterExecutionError: CMA process failed (undefined)",
      "",
      "                 Trace: spawn ENOMEM}",
      "",
      "",
      "",
      "                 STDERR: ",
      "    at invokeCumulusMessageAdapter (/var/task/webpack:/node_modules/@cumulus/cumulus-message-adapter-js/dist/cma.js:98:1)",
      "    at Object.runCumulusTask (/var/task/webpack:/node_modules/@cumulus/cumulus-message-adapter-js/dist/cma.js:172:47)",
      "    at Runtime.handler (/var/task/webpack:/index.js:159:10)"
    ]
  }
}
```

It appears that in such cases the lambda function is hitting the 256 MB memory limit. Unfortunately, Cumulus does not expose the memory configuration for its lambda functions, so there is no way to increase this.

One option is to move the PostToCmr lambda function to an ECS task, like the DiscoverGranules and QueueGranules lambda functions are currently configured (also due to memory [and duration] issues).

**Comment by chuckwondo** [comment]
I've posted the problem to the Cumulus slack channel, asking about moving PostToCmr to an ECS task, and whether that might require some tuning of the ECS cluster, given that both the DiscoverGranules and QueueGranule lambda functions have already been moved to ECS task due to memory/timeout issues.

While waiting for a response, I might try moving PostToCmr to an ECS task without any cluster tuning to see how it impacts performance, and also to confirm that such a move will eliminate the "out of memory" problem described above.
